### ISSUE TITLE
python course assignment 2

### ISSUE THREAD

**Issue by Lihierez** [Aish16032001/aishwarya.github.io#1]
Hi Aishwarya, 
you have a vary impressive website!
I would recommend, in the publications section, using more informative titles for your article rather than "Publication 1" (or using the article titles themselves if that works).

Best regards,
Lihi

**Comment by Aish16032001** [comment]
Thank you so much for the suggestion. I changed the title :). I will be happy to add if anything else is needed.

**Comment by Aish16032001** [comment]
@liroh99
