### ISSUE TITLE
Day02 assignment

### ISSUE THREAD

**Issue by AlonGersh** [Aish16032001/aishwarya.github.io#2]
Hi Aishwarya,

I'm reaching out as part of our Day 02 assignment. Your site looks clean and is very informative. I just have a small aesthetic suggestion: you might consider aligning your email with the image at the top of the page. Alternatively, you could create a new "Contact Info" section for it.

Good luck with your PhD and the course :)

**Comment by Aish16032001** [comment]
Thank you for the suggestion. I added contact info separately. Let me know if you have any other suggestions.I am happy to take that

**Comment by AlonGersh** [comment]
Looks great! 

@liroh99
